export const notificationTabs = ['All', 'Unread', 'Mentions'];

export const notificationsList = [
  {
    id: 1,
    type: 'spark',
    user: '@coder_jane',
    action: 'sparked your',
    target: "'React Hooks & Performance'",
    targetSuffix: 'code drop',
    avatar: 'https://api.dicebear.com/7.x/notionists/svg?seed=Jane',
    quote: '"This optimized the rerenders in my enterprise dashboard by 40%. Absolute gold!"',
    time: '2m ago',
    unread: true,
  },
  {
    id: 2,
    type: 'follow',
    user: 'dev_guru',
    action: 'followed you',
    target: '',
    targetSuffix: '',
    avatar: 'https://api.dicebear.com/7.x/notionists/svg?seed=Guru',
    details: '1 hour ago • Senior Backend at Vercel',
    time: '',
    unread: false,
    showFollowButton: true,
  },
  {
    id: 3,
    type: 'mention',
    user: 'Alex Chen',
    action: 'mentioned you in a comment on',
    target: 'Clean Architecture for Node.js',
    targetSuffix: '',
    avatar: 'https://api.dicebear.com/7.x/notionists/svg?seed=Chen',
    time: '3h ago',
    unread: false,
    showActionButtons: true,
  },
  {
    id: 4,
    type: 'comment',
    user: 'Marco Ross',
    action: 'commented on your snippet:',
    target: '"Tailwind Config for Dark Mode"',
    targetSuffix: '',
    avatar: 'https://api.dicebear.com/7.x/notionists/svg?seed=Marco',
    time: '5h ago',
    unread: false,
  },
  {
    id: 5,
    type: 'system',
    user: 'System Update:',
    action: 'Weekly Dev Stats for May 1st - May 7th are now available.',
    target: '',
    targetSuffix: '',
    avatar: null, // System icon handled in component
    details: 'You reached 500 sparks this week! Keep shipping.',
    time: '1d ago',
    unread: false,
  }
];
